language: node_js
matrix:
  include:
    - os: osx
      node_js: "8"
    - os: osx
      node_js: "9"
    - os: osx
      node_js: "10"
install:
  - npm install
script:
  - mkdir public
  - node --stack_size=100000 $(which npm) run build
  - npm run lint
  - npm run lint-styles
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
