name: deploy

on:
  push:
    branches: [ main ]
    push:
      tags:
      - 'v*'

jobs:
  # publish docker to GitHub registry
  deploy-docker:
    name: deploy/docker
    runs-on: ${{ matrix.os }}

    if: ${{ github.event_name == 'push' }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u orangemug --password-stdin
    - run: docker build -t docker.pkg.github.com/maputnik/editor/editor:main .
    - run: docker push docker.pkg.github.com/maputnik/editor/editor:main
